name: SE333_CI

on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:

      - name: checkout-repo
        uses: actions/checkout@v4

      # Set up Java
      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      # Install Checkstyle (Linter)
      - name: Install Linter
        run: |
          sudo apt-get install -y checkstyle

      # Run Checkstyle
      - name: Run Checkstyle
        run: |
          mvn validate  # Runs the Checkstyle plugin during the validate phase

      # Upload Checkstyle Result
      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

      # Run Maven Tests (with JaCoCo code coverage)
      - name: Run Maven Test
        run: |
          mvn test  # Runs Maven tests and collects JaCoCo coverage

      # Upload JaCoCo Coverage Report
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/index.html


